import tkinter as tk

window = tk.Tk()
window.title('Калькуль')
window.geometry('320x210')
window.resizable(False, False)
button_add = tk.Button(window, text = '+', width=4, height=2)
button_add.place(x=5, y=105)
button_sub = tk.Button(window, text = '-', width=4, height=2)
button_sub.place(x=55, y=105)
button_mul = tk.Button(window, text = '*', width=4, height=2)
button_mul.place(x=105, y=105)
button_div = tk.Button(window, text = '/', width=4, height=2)
button_div.place(x=155, y=105)
number1_entry = tk.Entry(window, width=50)
number1_entry.place(x=5, y=30)
number2_entry = tk.Entry(window, width=50)
number2_entry.place(x=5, y=80)
answer_entry = tk.Entry(window, width=50)
answer_entry.place(x=5, y=180)
number1 = tk.Label(window, text='Введите первое число:')
number1.place(x=5, y=5)
number2 = tk.Label(window, text='Введите второе число:')
number2.place(x=5, y=55)
answer = tk.Label(window, text='Ответ:')
answer.place(x=5, y=155)
window.mainloop()